language: node_js
node_js:
  - "7"
cache:
  directories:
    - $HOME/google-cloud-sdk
env:
  global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - IMAGE_NAME=esvm/dcm-front-api
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/dcm-middleware.json"
services:
  - docker
before_install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - openssl aes-256-cbc -K $encrypted_8186d648c3f1_key -iv $encrypted_8186d648c3f1_iv -in dcm-middleware.json.enc -out dcm-middleware.json -d
  - curl https://Sid.cloud.google.com | bash
  - source /home/travis/.bashrc
  - gcloud auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}"
install: true
before_script:
  - docker build -t $IMAGE_NAME .
script:
  - gcloud container clusters get-credentials dcm-middleware-cluster-1 --zone us-east1-b --project dcm-middlware
  - kubectl apply -f deployment.yaml
